# Generated by Django 3.2.6 on 2022-09-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email_address', help_text='Введите электронную почту', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='first_name', help_text='Введите имя(максимум 50 символов', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Выбери свой аватар', null=True, upload_to='users_avatars/', verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Укажите активен ли аккаунт', verbose_name='Аккаунт активен'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='last_name', help_text='Введите фамилию(максимум 50 символов', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите номер телефона', null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', help_text='Укажите роль', max_length=5, verbose_name='Роль пользователя'),
        ),
    ]
