# Generated by Django 3.2.6 on 2022-09-22 19:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220922_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Укажите номер телефона', max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
